stages:
  - test
  - build
  - deploy

lint_check:
  stage: test
  only:
    - main
    - feature
  image: python:3.9-slim-buster
  before_script:
    - pip install pylint
  script:
    - echo "Pylint check"
    # - pylint deps_manager/*  # Adjust this to lint your entire codebase

build:
  stage: build
  only:
    - main
    - feature
  image: python:3.9-slim-buster
  script:
    - python3 setup.py sdist bdist_wheel
  artifacts:
    paths:
      - "pypi_package/"